---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: frontend-deploy
  name: frontend-nginx-conf-file
  namespace: app
data:
  default.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
          proxy_http_version 1.1;
          proxy_pass http://backend-svc:5000;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
    }
