---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-svc
  name: backend-svc
  namespace: app
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 80
  selector:
    app: backend-deploy
